#!/bin/bash

###############################################################################
# 1. SELinux & 방화벽 비활성화
###############################################################################
echo "[1/8] SELinux & Firewalld 설정 중..."

# SELinux 설정 파일에서 enforcing -> disabled로 수정
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
# 현재 SELinux 상태도 즉시 Permissive로 변경 (재부팅 전까지 유효)
setenforce 0

# 방화벽 중지 및 비활성화
systemctl stop firewalld
systemctl disable firewalld

###############################################################################
# 2. DHCP 서버 설치 및 설정
###############################################################################
echo "[2/8] DHCP 서버 설치 및 설정 중..."

dnf -y install dhcp-server
systemctl enable --now dhcpd

# dhcpd.conf 설정 파일 작성
cat << 'EOF' > /etc/dhcp/dhcpd.conf
dhcpd_interface = "eth0";

subnet 192.168.0.0 netmask 255.255.255.0 {
        option routers 192.168.0.1;
        option subnet-mask 255.255.255.0;
        option domain-name-servers 8.8.8.8;
        default-lease-time 3600;
        max-lease-time 7200;
        allow booting;
        allow bootp;
        next-server 192.168.0.135;
        filename "pxelinux.0";
}

host dns {
  hardware ethernet 02:AA:00:00:01:36;
  fixed-address 192.168.0.136;
  option host-name "dns";
}

host storage {
  hardware ethernet 02:AA:00:00:01:37;
  fixed-address 192.168.0.137;
  option host-name "storage";
}

host db {
  hardware ethernet 02:AA:00:00:01:38;
  fixed-address 192.168.0.138;
  option host-name "db";
}

host controller1 {
  hardware ethernet 02:AA:00:00:01:20;
  fixed-address 192.168.0.120;
  option host-name "controller1";
}

host controller2 {
  hardware ethernet 02:AA:00:00:01:21;
  fixed-address 192.168.0.121;
  option host-name "controller2";
}

host controller3 {
  hardware ethernet 02:AA:00:00:01:22;
  fixed-address 192.168.0.122;
  option host-name "controller3";
}

host compute1 {
  hardware ethernet 02:BB:00:00:01:25;
  fixed-address 192.168.0.125;
  option host-name "compute1";
}

host compute2 {
  hardware ethernet 02:BB:00:00:01:26;
  fixed-address 192.168.0.126;
  option host-name "compute2";
}

host compute3 {
  hardware ethernet 02:BB:00:00:01:27;
  fixed-address 192.168.0.127;
  option host-name "compute3";
}
EOF

systemctl restart dhcpd

###############################################################################
# 3. FTP(vsftpd), TFTP, syslinux 설치 및 설정
###############################################################################
echo "[3/8] FTP, TFTP, syslinux 설치 및 설정 중..."

dnf -y install vsftpd tftp-server syslinux

# vsftpd.conf 에서 익명 로그인 허용
sed -i 's/^#\?anonymous_enable=.*/anonymous_enable=YES/g' /etc/vsftpd/vsftpd.conf

systemctl enable --now vsftpd
systemctl enable --now tftp

###############################################################################
# 4. Rocky 9.4 ISO 마운트 (FTP 경로)
###############################################################################
echo "[4/8] Rocky9 ISO 마운트 중..."

# rocky 9.5 ISO 파일 다운로드
#curl -O https://kr.mirrors.cicku.me/rocky/9.5/isos/x86_64/Rocky-9.5-x86_64-minimal.iso

# ISO 파일이 /root/rocky9.iso 에 있다고 가정하고 /var/ftp/pub 에 마운트
mount -t iso9660 /root/rocky9.iso /var/ftp/pub/

###############################################################################
# 5. TFTP 루트 디렉터리에 PXE 부트 관련 파일 복사
###############################################################################
echo "[5/8] TFTP 부트 파일 복사 중..."

cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot/
cp /var/ftp/pub/images/pxeboot/vmlinuz /var/lib/tftpboot/
cp /var/ftp/pub/images/pxeboot/initrd.img /var/lib/tftpboot/
cp /var/ftp/pub/isolinux/ldlinux.c32 /var/lib/tftpboot/

###############################################################################
# 6. pxelinux.cfg 디렉터리 및 기본 부팅 설정 파일 생성
###############################################################################
echo "[6/8] PXE 부팅 설정 작성 중..."

mkdir -p /var/lib/tftpboot/pxelinux.cfg

cat << 'EOF' > /var/lib/tftpboot/pxelinux.cfg/default
DEFAULT Rocky9_4gl_PXE
LABEL Rocky9_4gl_PXE
  kernel vmlinuz
  APPEND initrd=initrd.img inst.repo=ftp://192.168.0.135/pub inst.ks=ftp://192.168.0.135/rockypxe.ks
EOF

###############################################################################
# 7. Kickstart 파일 복사 및 수정
###############################################################################
echo "[7/8] Kickstart 파일 설정 중..."

# Kickstart 파일 덮어쓰기 예시 (필요 시 수정)
cat << 'EOF' > /var/ftp/rockypxe.ks
# Generated by Anaconda 34.25.5.9
# Generated by pykickstart v3.32
#version=RHEL9
# Use graphical install
graphical
%addon com_redhat_kdump --disable
%end

url --url=ftp://192.168.0.135/pub
keyboard --xlayouts='kr'
lang ko_KR.UTF-8

network  --bootproto=dhcp --device=eth0 --ipv6=auto --activate

%packages
@^minimal-environment
%end

firstboot --enable
ignoredisk --only-use=sda
autopart
clearpart --none --initlabel
timezone Asia/Seoul --utc

rootpw --iscrypted --allow-ssh $6$Qo94nAeqQJwVYbum$0MMYr7vAeXieqUCQuRY2/Aa9McJXPvU5I3ORhqn9Sl3fBj.hb5il4xUwCdsJvN/ICdvbuF2pKTmKIyiJCoNJP1

reboot
EOF

# rx 권한 부여
chmod 755 /var/ftp/rockypxe.ks


###############################################################################
# 8. 서비스 재시작
###############################################################################
echo "[8/8] 서비스 재시작..."

systemctl restart dhcpd
systemctl restart tftp
systemctl restart vsftpd

echo "PXE 서버 구성이 완료되었습니다."
