kubernetes_version: "v1.30"
crio_version: "v1.30"
controller_host: "controller1.example.com"
controller1: "172.16.0.110"
kubeconfig_path: "/etc/kubernetes/admin.conf"

k8s_nodes:
  controller1:
    ip_eth1: "172.16.0.120"
    prefix_eth1: "24"
    gw_eth1: "172.16.0.1"

    ip_eth2: "172.17.0.120"
    prefix_eth2: "16"
    gw_eth2: "172.17.0.1"

  controller2:
    ip_eth1: "172.16.0.121"
    prefix_eth1: "24"
    gw_eth1: "172.16.0.1"

    ip_eth2: "172.17.0.121"
    prefix_eth2: "16"
    gw_eth2: "172.17.0.1"

  controller3:
    ip_eth1: "172.16.0.122"
    prefix_eth1: "24"
    gw_eth1: "172.16.0.1"

    ip_eth2: "172.17.0.122"
    prefix_eth2: "16"
    gw_eth2: "172.17.0.1"

  compute1:
    ip_eth1: "172.16.0.125"
    prefix_eth1: "24"
    gw_eth1: "172.16.0.1"

    ip_eth2: "172.17.0.125"
    prefix_eth2: "16"
    gw_eth2: "172.17.0.1"

  compute2:
    ip_eth1: "172.16.0.126"
    prefix_eth1: "24"
    gw_eth1: "172.16.0.1"

    ip_eth2: "172.17.0.126"
    prefix_eth2: "16"
    gw_eth2: "172.17.0.1"

  compute3:
    ip_eth1: "172.16.0.127"
    prefix_eth1: "24"
    gw_eth1: "172.16.0.1"

    ip_eth2: "172.17.0.127"
    prefix_eth2: "16"
    gw_eth2: "172.17.0.1"
